from typing import Protocol


class Broker(Protocol):
    def place_order(self, payload: dict) -> dict: ...

    def cancel_order(self, symbol: str, order_id: str) -> dict: ...

    def get_order(self, symbol: str, order_id: str) -> dict: ...

    def get_exchange_info(self) -> dict: ...
